adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h zmalloc.h config.h ae_kqueue.c ae_epoll.c ae_select.c ae_evport.c
ae_epoll.o: ae_epoll.c
ae_evport.o: ae_evport.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
anet.o: anet.c fmacros.h anet.h
aof.o: aof.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
bitops.o: bitops.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
blocked.o: blocked.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
config.o: config.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h  \
 cluster.h
db.o: db.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h  \
 cluster.h
dict.o: dict.c fmacros.h dict.h zmalloc.h
intset.o: intset.c intset.h zmalloc.h config.h
multi.o: multi.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
networking.o: networking.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
notify.o: notify.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
object.o: object.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
pqsort.o: pqsort.c
pubsub.o: pubsub.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
quicklist.o: quicklist.c quicklist.h zmalloc.h ziplist.h util.h sds.h \
 lzf.h
rand.o: rand.c
rdb.o: rdb.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h  \
 lzf.h
redis-cli.o: redis-cli.c fmacros.h ../deps/hiredis/hiredis.h \
 ../deps/hiredis/sds.h zmalloc.h ../deps/linenoise/linenoise.h help.h \
 anet.h ae.h
release.o: release.c release.h crc64.h
replication.o: replication.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
rio.o: rio.c fmacros.h  sds.h util.h config.h server.h \
 ae.h \
 dict.h adlist.h zmalloc.h anet.h ziplist.h intset.h \
 quicklist.h rdb.h
scripting.o: scripting.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h  \
 rand.h \
 ../deps/lua/src/lualib.h
sds.o: sds.c sds.h sdsalloc.h zmalloc.h
sentinel.o: sentinel.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h  \
 ../deps/hiredis/hiredis.h ../deps/hiredis/async.h \
 ../deps/hiredis/hiredis.h
server.o: server.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c config.h
slowlog.o: slowlog.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
sort.o: sort.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h  \
 pqsort.h
sparkline.o: sparkline.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
syncio.o: syncio.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_hash.o: t_hash.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_list.o: t_list.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_set.o: t_set.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_string.o: t_string.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_zset.o: t_zset.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
util.o: util.c fmacros.h util.h sds.h sha1.h
ziplist.o: ziplist.c zmalloc.h util.h sds.h ziplist.h \
 config.h
zipmap.o: zipmap.c zmalloc.h config.h
zmalloc.o: zmalloc.c config.h zmalloc.h
