adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h zmalloc.h config.h ae_epoll.c
ae_epoll.o: ae_epoll.c
anet.o: anet.c fmacros.h anet.h
blocked.o: blocked.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
config.o: config.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
db.o: db.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
dict.o: dict.c fmacros.h dict.h zmalloc.h
intset.o: intset.c intset.h zmalloc.h config.h
multi.o: multi.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
networking.o: networking.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
object.o: object.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
pqsort.o: pqsort.c
quicklist.o: quicklist.c quicklist.h zmalloc.h ziplist.h util.h sds.h
redis-cli.o: redis-cli.c fmacros.h ../deps/hiredis/hiredis.h \
 ../deps/hiredis/sds.h zmalloc.h ../deps/linenoise/linenoise.h help.h \
 anet.h ae.h
sds.o: sds.c sds.h sdsalloc.h zmalloc.h
server.o: server.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h
sort.o: sort.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h  \
 pqsort.h
t_hash.o: t_hash.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_list.o: t_list.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_set.o: t_set.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_string.o: t_string.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
t_zset.o: t_zset.c server.h fmacros.h config.h \
 ae.h sds.h dict.h \
 adlist.h zmalloc.h anet.h ziplist.h intset.h util.h \
 quicklist.h 
util.o: util.c fmacros.h util.h sds.h
ziplist.o: ziplist.c zmalloc.h util.h sds.h ziplist.h \
 config.h
zipmap.o: zipmap.c zmalloc.h config.h
zmalloc.o: zmalloc.c config.h zmalloc.h
